//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackathonPMA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.EmployeeProjects = new HashSet<EmployeeProject>();
            this.FundProjects = new HashSet<FundProject>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string City { get; set; }
        public string Location { get; set; }
        public string Category { get; set; }
        public bool IsParent { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<double> TotalAllocatedAmount { get; set; }
        public Nullable<double> TotalSpentAmount { get; set; }
        public Nullable<int> ParentProjectId { get; set; }
        public Nullable<int> TotalSubProjects { get; set; }
        public string SubProjectIds { get; set; }
    
        public virtual ICollection<EmployeeProject> EmployeeProjects { get; set; }
        public virtual ICollection<FundProject> FundProjects { get; set; }
    }
}
